### ISSUE TITLE
Fix family page flag emojis on Windows

### ISSUE THREAD

**Issue by lucashu1** [Duet-USC/duet#84]
We currently have our country flags defined as unicode emojis in `packages/frontend/constants/flags.js`.

However, Windows 10 [doesn't actually support](https://blog.getemoji.com/post/620280709025841152/how-to-use-flag-emojis-on-windows) flag emojis :(
It looks like it just renders "US" instead of showing the emoji image.

So on our family page, the country flag emojis in the "Meet the __ Family" section and in the "Recently Donated" section don't render properly.

For better cross-platform support, what we could do instead is use actual PNG files instead of emojis. You can find PNGs for each emoji at https://emojipedia.org/flags/, e.g. https://emojipedia.org/flag-afghanistan/. Let's standardize on the "Apple" version for now. We can create a `flagPngs` (or something like that) under `constants`, where each entry is the image source URL for a given flag PNG. For now, we can just support the same countries that are currently in `flags.js`.

For help on scaling the PNGs according to the font size: https://stackoverflow.com/questions/18435777/adjust-image-size-based-on-the-font-size

A "nice-to-have" would be to use PNGs on Windows only, and stick with emojis on all other platforms. We currently use `UserAgentContext` (a React [context](https://reactjs.org/docs/context.html)) to inject information on the current user's platform down into the lower-level React components. Currently, we only use it track whether the user is on desktop or not, but we could modify it to track whether the user is on Windows as well.

Then, depending on the state of `UserAgentContext`, we can either use the flag emoji directly (all platforms except Windows), or render the flag PNG in an `<img>` tag instead (only on Windows).

The `context` part may prove tricky, so reach out if any questions come up! If using the context proves too difficult, we could just fall back to using flag PNGs on all platforms.

**Comment by washingtonzhao** [comment]
Prelim solution (pngs) before using contexts #87
